version: '3.8'

services:
  backend:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/ai-devops-tracker
      - JWT_SECRET=your_secret_key
      - GEMINI_API_KEY=your_gemini_key
    depends_on:
      - mongodb

  frontend:
    build: ./client
    ports:
      - "5173:5173"
    depends_on:
      - backend

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
